run:
  timeout: 5m
  tests: true

linters:
  enable:
    - vet
    - fmt
    - goimports
    - errcheck
    - staticcheck
    - unused
    - gosimple

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-use-default: false
